config/routes.rb
OneTo43::Application.routes.draw do

  get "photos/index"

  devise_for :users, :path_names => {:sing_up => "register"}

  get "welcome/index"
  get "welcome/about", :as => "about"

  resources :cars do
    member do
      post :subscribe_user
      post :unscribe_user
    end
    resources :photos 
  end

  namespace :cabinet do
    resources :photos
    resources :cars
  end

  root :to => "welcome#index"

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :title, :presence =>true, :length => { :minimum => 4 } 
  has_many :photos
  has_and_belongs_to_many :users
 
  def to_param
    title
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_attached_file :photo,
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension",
		  :styles => {:medium =>"120x120>", :large => "600x600>"} 

	validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
        belongs_to :car
        belongs_to :user
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable :confirmable,
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  has_many :photos
  has_and_belongs_to_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from ActiveRecord::RecordNotFound, :with => :rescue_from_not_found

  private

  def rescue_from_not_found(exception)
    @exception = exception
    render :file => "shared/404", :status => 404
  end

end

app/controllers/cabinet/cars_controller.rb
class Cabinet::CarsController < ApplicationController
  before_filter :find_object, :only => [:edit, :show, :update, :destroy]
  
  def index
    @cars = current_user.cars.paginate(:page => params[:page], :per_page =>Settings.count_cars_in_page)
  end

  def show
  end

  def new
    @car = current_user.cars.new
  end

  def edit
  end

  def create
    @car = current_user.new(params[:car])
    if @car.save
      flash[:notice] = "Successfully created!"
      redirect_to cabinet_cars_path(@car)
    end
  end
  
  def update
  end

  def destroy
    current_user.cars.remove(@car)
  end
  private

  def find_object
    @car = current_user.cars.find_by_title(params[:id])
    raise ActiveRecord::RecordNotFound, "Could not find the car '#{params[:id]}'" unless @car
  end

end

app/controllers/cabinet/photos_controller.rb
class Cabinet::PhotosController < ApplicationController

  def index
    @photos = current_user.photos.paginate(:page => params[:page])
  end

  def show
    @photo = current_user.photos.find(params[:id])
  end
  
  def new
    @photo = current_user.photos.new
  end
	
  def create
    @photo = current_user.photos.create(params[:photo])
    if @photo.save
      flash[:notice] = I18n.t("Successfully created!")
      redirect_to cabinet_photos_path(params[:car_id])
    else
      flash[:notice] = "failed"
      redirect_to cabinet_new_photo_path(params[:car_id])
    end
  end
	
  def edit
    @photo = current_user.photos.find(params[:id])	
  end
	
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_filter :find_object, :only => [:edit, :show, :update, :destroy, :subscribe_user]
  before_filter :require_user_logged, :only => :subscribe_user
  
  def index
    @cars = Car.paginate(:page => params[:page], :per_page =>Settings.count_cars_in_page)
  end

  def show
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(params[:car])
    if @car.save
      flash[:notice] = "Successfully created!"
      redirect_to car_path(@car)
    else
      redirect_to new_car_path
    end
  end
  
  def update
  end

  def destroy
    @car.destroy
  end

  def subscribe_user
    @car.users << current_user
    render :text => "subscribed"
    #redirect_to cars_path
  end

  private

  def find_object
    @car = Car.find_by_title(params[:id])
    raise ActiveRecord::RecordNotFound, "Could not find the car '#{params[:id]}'" unless @car
  end

  def require_user_logged
    unless current_user
      flash[:error] = t("must_be_logged_in")
      redirect_to cars_path
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	
	before_filter :find_car, :only => [:index, :new, :edit, :create, :show, :update, :destroy]

	def index
                @photos = @car.photos.paginate(:page => params[:page], :per_page => 9)
	end
	
	def show
		@photo = @car.photos.find(params[:id])
	end

	
	def update
		
	end

	
	def destroy
	       photo = @car.photos.find(params[:id])
               photo.destroy
	end

        private

  	def find_car
    		@car = Car.find_by_title(params[:car_id])
    		raise ActiveRecord::RecordNotFound, "Could not find the car '#{params[:id]}'" unless @car
 	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	@count_cars = Settings.count_view_cars
	@count_all_cars = Car.count
	@count_cars = [@count_cars,@count_all_cars].min
	@cars = Car.all(:order => 'RANDOM()',:limit => @count_cars)
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def page_title 
    @page_title or t("default_page_title")
  end

end

app/helpers/cabinet/cars_helper.rb
module Cabinet::CarsHelper
end

app/helpers/cabinet/photos_helper.rb
module Cabinet::PhotosHelper
end

app/helpers/cars_helper.rb
module CarsHelper
  def info_view_car(count_cars,count_all_cars) 
    result = t("articles_in_auto_wiki")
    result += " ( "
    result += count_cars
    result +=" "+t("of")+" "
    result +=count_all_cars
    if count_cars>count_all_cars
      result+=link_to t("all"), cars_path
    end
    result += " ) "
    result 
  end

  def car_photo(car)
    photos = car.photos
    if photos.length > 0 
      photo = photos.offset(rand(car.photos.count)).first 
      image_tag photo.photo.url(:medium)    
    else
      image_tag "rails.png" 
    end
  end

  def subscribe_car(car)
    if current_user
      if current_user.cars.include?(car)
        link_to "[-]", unscribe_user_car_path(car), :method => :post
      else
        link_to "[+]", subscribe_user_car_path(car), :method => :post  
      end
    end
  end
end

app/helpers/page_title_helper.rb
module PageTitleHelper
  @page_title = "Test"
end

app/helpers/photos_helper.rb
module PhotosHelper
  def gallery_photo(photo, options = {})
    content_tag :div do
      link_to (image_tag "rails.png"),  :id =>photo.id, :car_id => params[:car_id],  :method =>:delete , :class => "deliting"
      link_to (image_tag photo.photo.url(:medium)), photo.photo.url(:large) , :class => "gallery"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cabinet/cars/_form.html.haml
= form_for @car, :html => { :multipart => true }  do |f|
    = f.text_field :title
    = f.text_area :wiki
    = f.submit 'Save'

app/views/cabinet/cars/_leftbar.html.haml
left

app/views/cabinet/cars/_onecar.html.haml
- for car in @cars
  %br
  %p
    %strong=car.title
  %p=truncate(car.wiki, :length => 100) 
  %p
    =link_to t("detail"), car 
    =link_to t("edit"), edit_car_path(car)
    =link_to t("delete"), car, :confirm => 'Are you sure?', :method => :delete

app/views/cabinet/cars/_rightbar.html.haml
right

app/views/cabinet/cars/edit.html.haml
%h1 Editing car

= render 'form'

= link_to t("upload_photos"), cabinet_new_car_photo_path(@car.title)
\|
= link_to t("show"), @car
\|
= link_to t("all_cars"), cabinet_cars_path

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cabinet/cars/index.html.haml
=content_tag :head do
  = stylesheet_link_tag "pagination"
%h1 
  =t("listing_car")
#pages.flickr_pagination
  =will_paginate @cars, :container => false

= render :partial => 'onecar'
%br
= link_to t("add_car"), new_cabinet_car_path

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cabinet/cars/new.html.haml
%h1 New car

= render 'form'

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cabinet/cars/show.html.haml
%p#notice= notice
=car_photo (@car) 
%p 
  %b Title:
  = @car.title
%p
  %b Wiki:
  = @car.wiki


= link_to t("edit"), cabinet_edit_car_path(@car)
\|
= link_to t("all_cars"), cabinet_cars_path

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cabinet/photos/_form.html.haml
- form_for [:cabinet, @photo], :html => { :multipart => true } do |item|
   %p= item.file_field :photo
   %p= item.submit t("submit_upload")

app/views/cabinet/photos/_leftbar.html.haml
left

app/views/cabinet/photos/_photo.html.haml
.picture 
  .photo
    =link_to (image_tag photo.photo.url(:medium)), photo.photo.url(:large) , :class => "gallery_fancy"            
  .deliting
    =link_to image_tag("close.png"),  cabinet_photo_path(photo), :method =>:delete 

app/views/cabinet/photos/_rightbar.html.haml
right

app/views/cabinet/photos/index.html.haml
=content_for :head do
  = javascript_include_tag "jquery.js", "jquery_ujs"
  = javascript_include_tag "gallery.js"
  = javascript_include_tag "/fancybox/jquery.fancybox-1.3.4.js"
  = stylesheet_link_tag "/fancybox/jquery.fancybox-1.3.4.css"
  = stylesheet_link_tag "pagination"
  = stylesheet_link_tag "gallery"

= t("all_photos")
.bar  
  .left.column 
    .flickr_pagination
      =will_paginate @photos, :container => false
  .right.column
    =link_to (image_tag "plus.png"), new_cabinet_photo_path(params[:car_id])

  -#gallery
    =gallery(@photos)
  .gallery
    = render :partial => "photo", :collection => @photos


- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cabinet/photos/new.html.haml
%p= t("upload_photos")

= render :partial => 'form'

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cabinet/photos/show.html.haml
=image_tag @photo.photo.url

app/views/car/index.html.haml
= render :partial => "photos"

%p= link_to t("upload_photos"), upload_car_path

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cars/_car.html.haml
%div{:id => "car-#{car.id}"}
  %p
    %strong=car.title
    =subscribe_car(car)
  %p=truncate(car.wiki, :length => 100) 
  %p
    =link_to t("detail"), car 
    =link_to t("edit"), edit_car_path(car)
    =link_to t("delete"), car, :confirm => 'Are you sure?', :method => :delete

app/views/cars/_leftbar.html.haml
left

app/views/cars/_onecar.html.haml
%div{:id => "car-#{car.id}"}
  %p
    %strong=car.title
    =subscribe_car(car)
  %p=truncate(car.wiki, :length => 100) 
  %p
    =link_to t("detail"), car 
    =link_to t("edit"), edit_car_path(car)
    =link_to t("delete"), car, :confirm => 'Are you sure?', :method => :delete

app/views/cars/_rightbar.html.haml
right

app/views/cars/edit.html.haml
%h1 Editing car

= render 'form'

= link_to t("upload_photos"), new_car_photo_path(@car.title)
\|
= link_to 'Show', @car
\|
= link_to 'Back', cars_path

app/views/cars/index.html.haml
=content_tag :head do
  = stylesheet_link_tag "pagination"
%h1 
  =t("listing_car")
#pages.flickr_pagination
  =will_paginate @cars, :container => false

= render :partial => 'car', :collection => @cars
%br
= link_to t("add_car"), new_car_path

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/cars/new.html.haml
%h1 New car

= render 'form'

app/views/cars/show.html.haml
%p#notice= notice
%table
  %td
    = car_photo (@car) 
  %td
    %p
      %b Title:
      = @car.title
    %p
      %b Wiki:
      = @car.wiki


= link_to 'Edit', edit_car_path(@car)
\|
= link_to 'Back', cars_path

app/views/layouts/application.html.haml
!!! Strict
%html{:lang => "en", "xml:lang" => "en", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = yield(:head) 
    %title= "page_title"
    
  %body
    #header.container_12
      .grid_12= render :partial => "shared/header"

    #content.container_12
      #leftbar.grid_3= yield(:leftbar)
      #content.grid_6= yield
      #rightbar.grid_3= yield(:rightbar)

    #footer.container_12
      .grid_12= render :partial => "shared/footer"

app/views/photo/index.html.haml
= render :partial => "photos"

%p= link_to t("upload_photos"), upload_photo_path

- content_for :leftbar do
  = render :partial => 'leftbar'

- content_for :rightbar do
  = render :partial => 'rightbar'

app/views/photos/index.html.haml
=content_for :head do
  = javascript_include_tag "jquery.js"
  = javascript_include_tag "gallery.js"
  = javascript_include_tag "/fancybox/jquery.fancybox-1.3.4.js"
  = stylesheet_link_tag "/fancybox/jquery.fancybox-1.3.4.css"
  = stylesheet_link_tag "pagination"
  = stylesheet_link_tag "gallery"
= t("all_photos")
.bar  
  .left.column 
    .flickr_pagination
      =will_paginate @photos, :container => false
  .right.column
    =link_to (image_tag "plus.png"), new_car_photo_path(params[:car_id])

  -#gallery
    =gallery(@photos)
  .gallery
    -@photos.each do |photo|
      .picture 
        .photo
          =link_to (image_tag photo.photo.url(:medium)), photo.photo.url(:large) , :class => "gallery_fancy"            
  - content_for :leftbar do
    = render :partial => 'leftbar'

  - content_for :rightbar do
    = render :partial => 'rightbar'

app/views/photos/show.html.haml
= image_tag @photo.photo.url

app/views/shared/404.html.haml
%h1 Record not found

%p 
  The error was:
  = @exception.message

= link_to "Home", root_path

app/views/shared/_footer.html.haml
%p= link_to t("main_page"), root_path

app/views/shared/_header.html.haml
%p header

app/views/welcome/_cabinet.html.haml
cabinet

app/views/welcome/_cars.html.haml
%h3.title  
  = info_view_car(@count_cars.to_s, @count_all_cars.to_s)
- for item in @cars
  %br
  %strong= item.title
  %p=truncate(item.wiki, :length => 100) 
  %p= link_to(t("detail"), item )
= link_to(t("add_car"), new_car_path)

app/views/welcome/_leftbar.html.haml
-if user_signed_in?
  %p Signed in as user
  = current_user.email
  =link_to("Sign out",destroy_user_session_path)  
-else
  %p Email
  %input
  %p Password
  =password_field_tag
  %p= link_to("Sing Up",new_user_registration_path)
  %p= link_to("Sing in",new_user_session_path)
%p= render :partial => "cabinet"

app/views/welcome/_photos.html.haml
%p= t("popular_photos")
-#%p= link_to t("all_photos"), photos_path

app/views/welcome/about.html.haml
%h1 Welcome#about
%p Find me in app/views/welcome/about.html.haml
%p about

app/views/welcome/index.html.haml
= render :partial => "photos"
= render :partial => "users"
= render :partial => "cars"

- content_for :leftbar do
  = render :partial => 'leftbar'


- content_for :rightbar do
  = render :partial => 'rightbar'